# Generated by Django 3.2.5 on 2021-08-04 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.IntegerField(default=254),
        ),
    ]
