# Generated by Django 3.2.5 on 2021-08-04 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidapp', '0002_contacttracing_doctorsinput_location_patientinput'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorsinput',
            name='recomendations',
            field=models.IntegerField(choices=[(1, 'Hospital Care'), (2, 'Home Care')], default=0),
        ),
    ]
