# Generated by Django 3.2.5 on 2021-08-13 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covidapp', '0003_auto_20210810_1031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorsinput',
            name='date',
        ),
        migrations.RemoveField(
            model_name='patientinput',
            name='date',
        ),
    ]
