# Generated by Django 3.2.5 on 2021-08-07 06:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('covidapp', '0006_alter_patientinput_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientinput',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to=settings.AUTH_USER_MODEL),
        ),
    ]
